### ISSUE TITLE
one more silly question

### ISSUE THREAD

**Issue by fengyuchengdu** [xavierdidelot/BactDating#11]
Hi Xavier,

I'm just wondering how can I translate the coordinates/values of the internal nodes (e.g. a node of 3.123 with 95% CI of -8.679 to 12.369) to the real time in years (e.g. 2000.369 with CI 1998.348 to 2003.782). 

Is there any table, like the one in BEAST which allows you to see how real time data is converted into values? 

many thanks,

Yu

**Comment by xavierdidelot** [comment]
The res$CI already contains dates in real time, but if somehow you've lost this in your processing of the output, maybe you can convert from relative to real time using the date of the root which is stored in res$tree$root.time

**Comment by mmaesaar** [comment]
How to associate res$CI with the res$tree$node.label ?
