### ISSUE TITLE
How to set evolutionary clock

### ISSUE THREAD

**Issue by mmaesaar** [xavierdidelot/BactDating#19]
Is it possible and how to set evolutionary clock for example 3.0x10-5 substitutions per site per year?

**Comment by xavierdidelot** [comment]
Yes it is possible, for that you need to use the arguments "initMu=..." to set the clock rate and also "updateMu=F" to stop it from being updated. The value you set it to should be express for the whole genome, not per site. So if your genome is of length 1Mbp and you want a clock of 3e-5 per site per year, then you should use "initMu=30"

**Comment by mmaesaar** [comment]
Thank you for your answer - works fine and MCMC parameters are also >200, except for mu which is 0. But am I correct that it is due to fact that initMu is set and updateMu is disabled?

**Comment by xavierdidelot** [comment]
Yes that's right.
