### ISSUE TITLE
Consider STAN as an MCMC engine

### ISSUE THREAD

**Issue by andersgs** [xavierdidelot/BactDating#2]
Hello.

I have not tried BactDating yet, but I am keen. 

From a quick glance at the code, and from my reading of the paper, I am wondering why you did not consider using STAN to run the MCMC?

It is fast, there is a considerable amount of development that has gone into it, there are associated libraries to help with model selection and assessment (e.g., `loo`), useful libraries for visualisation (e.g., `bayesplot` and `ShinyStan`), and they provide tools to help package precompiled binaries of the models with R (package `rstantools`).

More information here: http://mc-stan.org/users/interfaces/rstan and here http://mc-stan.org/users/interfaces/

Best. A.

**Comment by tseemann** [comment]
@xavierdidelot any reason for closing this without a response?

**Comment by xavierdidelot** [comment]
I have plans for extensions of BactDating and don't want to be tied down to a specific MCMC engine.

**Comment by tseemann** [comment]
Thank you.
