### ISSUE TITLE
Write result tree to nexus

### ISSUE THREAD

**Issue by ConstantinV** [xavierdidelot/BactDating#22]
Hi! Thank you for BactDating.
I wonder, how to write tree (after analysis) in nexus format with CI values for each node? I need to open this tree in Figtree for detailed analysis.

**Comment by xavierdidelot** [comment]
Hi Constantin,
I had to make a small change to the BactDating code to get this to work, so please update to the latest version 1.0.7. You should then be able to use the following code to export to a nexus file for FigTree:

```
library(BactDating)
res=bactdate(...)
l=as.treedata.resBactDating(res)
library(treeio)
obj=methods::new('treedata',phylo=l[[1]],data=dplyr::tbl_df(as.data.frame(l[[2]])))
write.beast(obj,'test.nex')
```

**Comment by ConstantinV** [comment]
Thank you so much for the fast response!
