### ISSUE TITLE
pstrict value explanation!

### ISSUE THREAD

**Issue by nbawe** [xavierdidelot/BactDating#25]
Hello what is pstrict value and how to interpreted?
For example:

```
res=bactdate(tree,dates,useRec=T)
res$pstrict
## [1] 0
```

Thank you

**Comment by xavierdidelot** [comment]
This is the probability that the clock is strict, rather than relaxed. If this value is zero, it means that a relaxed clock is definitely preferred.

**Comment by nbawe** [comment]
So if I used default `res=bactdate(tree,dates,useRec=T)` command and by default model is `mixedgamma` then pstrict indicates relaxed clock - should I rerun analysis with `relaxedgamma` or `mixedgamma` already used relaxed model?

**Comment by xavierdidelot** [comment]
No there is no need to rerun, because pstrict=0 indicates that a strict clock was always rejected and therefore never used. So the output of relaxedgamma would be the same as the output of mixedgamma.

**Comment by nbawe** [comment]
Thank you - very much.
