### ISSUE TITLE
Posterior support values of the result tree?

### ISSUE THREAD

**Issue by Tonny-zhou** [xavierdidelot/BactDating#26]
Hi! Thank you for BactDating.

I' am a newcomer to the phylogenetic filed. I wanna know whether the result tree has posterior support values for each nodes.

Thank you

**Comment by xavierdidelot** [comment]
Hi Tonny,

BactDating uses a phylogeny as input to infer a dated phylogeny. The nodes in the output are the same as in the input, so there is no posterior support value being computed, except for the location of the root which is inferred if you use updateRoot=T (which is the default). You can access the posterior probability of the root via res$rootprob

Best wishes,
Xavier

**Comment by Tonny-zhou** [comment]
Thank you!
