### ISSUE TITLE
Error in if (log(runif(1)) < l2 - l + pratio + qratio) { :    missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by nbawe** [xavierdidelot/BactDating#27]
Hi when running following command I get the error:

`t=loadCFML("/Users/cfml_output")` and dates as an intervals

`res=bactdate(t,d,initMu=32.6,updateMu=F,nbIts=1000000, useRec=T, showProgress=T)`

ERROR:
```
Error in if (log(runif(1)) < l2 - l + pratio + qratio) { : 
  missing value where TRUE/FALSE needed
```

When using single dates set to equal to estimate divergence same error occurres:

`t=loadCFML("/Users/cfml_output")` and dates forced equal

`res=bactdate(t,d,initMu=32.6,updateMu=F,nbIts=1000000, useRec=T, showProgress=T)`

ERROR:
```
Error in if (log(runif(1)) < l2 - l + pratio + qratio) { : 
  missing value where TRUE/FALSE needed
```

Using `BactDating v1.0.8`

Do you have any idea what it could be?

**Comment by xavierdidelot** [comment]
After the `loadCFML` command, could you check if any of the `t$unrec` is negative or undefined?

**Comment by nbawe** [comment]
No negatives and no undefined values.

**Comment by xavierdidelot** [comment]
Are all values in `t$unrec` between 0 and 1 ?

**Comment by nbawe** [comment]
Yes:
> min = 0,95099521
> max = 0,99999355

**Comment by xavierdidelot** [comment]
Ok there's really nothing wrong with that then. 
1) Does it work with `unrec=F` instead of `unrec=T`?
2) Does it work if you add `model=relaxedgamma` ?
3) Does it work if you add `model=strictgamma` ?

**Comment by nbawe** [comment]
Well that is more than wierd, just ran the same script again that I used and everything works as intended.

I have ran this script before many times and the error was printed.

Thanks for the help and sorry for the confusion.

**Comment by xavierdidelot** [comment]
The only explanation I see is that there was something wrong previously in your `t$unrec`, but I'm glad this is now solved for you!

**Comment by mmaesaar** [comment]
[Link](https://groups.google.com/forum/#!topic/raxml/S2B60psdtkw) to Alexis answer in RAxML Google Group
