### ISSUE TITLE
95%CI association with tip and node labels?

### ISSUE THREAD

**Issue by mmaesaar** [xavierdidelot/BactDating#29]
Hello,

regarding issues #11 and #17 what is the correct order of CIs in `res$CI` - it seems that first there are tips (`res$tree$tip.label`) and then nodes (`res$tree$node.label`)?

Is this correct way to associate CIs with tip and node labels:

1) Combining tree tip and node labels from res object:
`combined <- c(res$tree$tip.label,res$tree$node.label)`

2) Combining previous object (combined) with CIs:
`combinedCIs <- cbind(combined,res$CI)`

Thank you!

**Comment by xavierdidelot** [comment]
Yes that's exactly it!

**Comment by mmaesaar** [comment]
Thank you
