### ISSUE TITLE
bug in loadGubbins function?

### ISSUE THREAD

**Issue by amilesj** [xavierdidelot/BactDating#3]
I am getting an error that says : `cannot open file '{prefix}.node_labelled.tre'` But in my Gubbins output, the file is named `{prefix}.node_labelled.final_tree.tre`

**Comment by xavierdidelot** [comment]
Hi Arianna,
Thanks for reporting this, and sorry for the delayed reply - I'm only just back from Summer holiday. I have just committed an update to BactDating that should solve this issue.
Best wishes,
Xavier
