### ISSUE TITLE
export to figtree

### ISSUE THREAD

**Issue by fengyuchengdu** [xavierdidelot/BactDating#30]
Hi Xavier,

I followed your reply in https://github.com/xavierdidelot/BactDating/issues/21#issuecomment-555908896 to export BactDating result.

library(treeio)
l=as.treedata.resBactDating(e6_mixed)
obj=methods::new('treedata',phylo=l[[1]],data=dplyr::tbl_df(as.data.frame(l[[2]])))
write.beast(obj,'e6_mixed.nex')

No matter how I chose to display in "Node Bars" of figtree (height_0.95_HP or length_0.95_HP), the interval bars were detached from their corresponding node (images at the bottom).

Thanks for your help,

Yu

plot in R
![image](https://user-images.githubusercontent.com/17246742/84976021-76b4fd80-b159-11ea-94a9-a19c559312d4.png)

open in figtree
![Screenshot from 2020-06-18 11-19-03](https://user-images.githubusercontent.com/17246742/84976053-83395600-b159-11ea-9e2a-edb9fb8bfb38.png)

**Comment by xavierdidelot** [comment]
That's annoying and I'm not sure why it's happening in your case but not others. 
Maybe you could try in FigTree on the lefthand side to click "Time scale" and then change the "Offset by" factor to realign the bars to the nodes. 
If that does not help I would need a RData file containing the object e6_mixed to investigate further.

**Comment by fengyuchengdu** [comment]
Adjusting "Time scale" and "Offset by" in FigTree had no effect on node bars. However, I repeated the analysis on the same data but with modified strain names (made it simpler to e.g. strain1) and the problem disappeared.

I'm gonna run a few more tests and get back to you soon, Thanks.

**Comment by fengyuchengdu** [comment]
Sorry, I figured it out. 
It somehow passed the tip-date-name-mismatch-checker and ran through without throwing out an error, but there was a single mismatch between a date-tip pair. 
The problem went away after amending accordingly. 
Thanks for the help.

**Comment by xavierdidelot** [comment]
I'm pleased it is now working for you, thanks for letting me know!

**Comment by fengyuchengdu** [comment]
Sorry to reopen this, but the problem came again. 
[RData.zip](https://github.com/xavierdidelot/BactDating/files/4841850/RData.zip)
I've uploaded the Rdata file and thanks much.

**Comment by xavierdidelot** [comment]
I have just submitted a new version 1.0.12 which should solve your problem.

**Comment by fengyuchengdu** [comment]
It works now, thanks !
