### ISSUE TITLE
How to export BactDating tree to newick?

### ISSUE THREAD

**Issue by mmaesaar** [xavierdidelot/BactDating#31]
I have trouble exporting BactDating tree to newick format for further analysis with [treestructure](https://github.com/emvolz-phylodynamics/treestructure). Could someone share how to export it to newick?

Thank you!

**Comment by mmaesaar** [comment]
I think I found solution that works 
`write.tree(res$tree, file = 'outfile.nwk')`

**Comment by xavierdidelot** [comment]
Yes that's right, well done for finding it by yourself!
