### ISSUE TITLE
Can BactDating run on R3.6.1?

### ISSUE THREAD

**Issue by StephanieWLo** [xavierdidelot/BactDating#34]
I have tried to run BactDating using R3.6.1 and got the error message. Not sure if that's due to R version. Please kindly advise. Thank you.

Error in CI[i, 1] <- s[ceiling(length(s) * 0.025)] : 
  replacement has length zero
Calls: bactdate
Execution halted

**Comment by xavierdidelot** [comment]
Hi Stephanie,

I'm pretty sure that this error is not related to your R version.
If you are still having this problem, could you please reopen this issue and paste your exact command line.

Best wishes,
Xavier

**Comment by StephanieWLo** [comment]
Hi Xavier,

Sorry for my silly question and thank you for your reply. The error message is probably because mcmc chain length was set smaller than ceilling(10000). The error did not pop up again once set it >10000. Thank you.

Best wishes,

Steph

**Comment by xavierdidelot** [comment]
I think you should be able to run even for a small number of iterations (eg nbIts=1), but anyway I'm glad this problem is solved for you.
