### ISSUE TITLE
seems like the as.mcmc function behaves differently between R versions

### ISSUE THREAD

**Issue by fengyuchengdu** [xavierdidelot/BactDating#36]
ape = 5.4
coda = 0.19-3
BactDating = 1.0.12
the installed version of these 3 are the same

when running "
mcmc=as.mcmc(result)
effectiveSize(mcmc) 
" on the same result

R 3.6.3 processed as expected, however in R 4.0.2, it showed "Error in character(ncol(y)) : invalid 'length' argument"

after checking "mcmc", it seems to contain more than 3 columns and include CI data etc. when using R 4.0.2

**Comment by xavierdidelot** [comment]
Hi Feng,

Could you please check if it works when you use:
`mcmc=as.mcmc.resBactDating(res)`
instead of
`mcmc=as.mcmc(res)`

Best wishes,
Xavier

**Comment by fengyuchengdu** [comment]
Yes, it worked, thanks for the solution

**Comment by xavierdidelot** [comment]
Thanks for confirming, and I will try to make `as.mcmc` work soon too.
