### ISSUE TITLE
Please Host BactDating on the Anaconda R Channel

### ISSUE THREAD

**Issue by dnanto** [xavierdidelot/BactDating#37]
I've included BactDating in a Snakemake workflow and it works great. For reproducibility, I would like to list it as a dependency in a conda YAML file. This would require building and hosting this package on [Anaconda](https://anaconda.org/r/repo). I saw a possible solution on [StackOverflow](https://stackoverflow.com/a/52475507).

If you are too busy, I could look into doing it myself if you don't have an issue with me doing so. Never tried it myself, but it seems doable. Anyway, thank you for this package, looking forward to citing it in my dissertation. Either way, I came up with a hack that works for now.

**Comment by xavierdidelot** [comment]
Yes I think it is relatively easy to turn a R package into a conda package. For example I know someone did it for my other package TransPhylo, cf https://anaconda.org/bioconda/r-transphylo

I don't really know it is done though, so if you or anybody else could volunteer this would be great!

**Comment by dnanto** [comment]
Cool, I'll give it a shot, I'll post the steps I took here.

**Comment by dnanto** [comment]
Ran this:
```bash
conda skeleton cran https://github.com/xavierdidelot/BactDating
conda build r-bactdating
```

Then, created a [pull request](https://github.com/conda-forge/staged-recipes/pull/12550) on the conda-forge channel.
