### ISSUE TITLE
Invariant sites for snp tree?

### ISSUE THREAD

**Issue by Tonny-zhou** [xavierdidelot/BactDating#43]
Hi! Thank you for BactDating.

I' am a newcomer to the phylogenetic filed. I find that the output of the substitution rate from BactDating for the tree based on only the snp sites is large than those previously reported (for the strain staphylococcus aureus). I want to know whether it is due to lacking the invariant sites?

Thank you

**Comment by xavierdidelot** [comment]
Hi Tonny,

Yes indeed if your tree was built using SNPs only then you should rescale the branches of this tree before running BactDating. To rescale you can use something like:
`tree$edge.length=tree$edge.length*L`
where `L` is the genome length and `tree` is the tree based on SNPs with branch lengths measured per site.

**Comment by Tonny-zhou** [comment]
> Hi Tonny,
> 
> Yes indeed if your tree was built using SNPs only then you should rescale the branches of this tree before running BactDating. To rescale you can use something like:
> `tree$edge.length=tree$edge.length*L`
> where `L` is the genome length and `tree` is the tree based on SNPs with branch lengths measured per site.


Does the  genome length include the invariant sites?

**Comment by xavierdidelot** [comment]
Yes by "genome length" I mean the length of the whole genome including invariant sites.
