### ISSUE TITLE
questions on interpreting results

### ISSUE THREAD

**Issue by fengyuchengdu** [xavierdidelot/BactDating#44]
Hi Xavier,

1) I'm definitely not a math person and having some difficulties in understanding the parameter alpha. Could you please explain the "coalescent time unit" in an example?

2) If previous recombination analysis is used (e.g. Gubbins), the final mu represents the substitution rate outside the recombination region only, not the whole genome?

Many thanks

**Comment by xavierdidelot** [comment]
Hi Feng,

alpha is the average time it takes for two lineages to find a common ancestor. alpha is equal to Ne*g where Ne is the effective population size and g is the duration of a generation.

yes indeed, if you apply BactDating to a tree which is the output of Gubbins or ClonalFrameML then the mu estimated corresponds to the substitution rate in unrecombined regions.

Best wishes,
Xavier
