### ISSUE TITLE
Question about the strength of signal requirements.

### ISSUE THREAD

**Issue by martinastoycheva** [xavierdidelot/BactDating#46]
Hello Professor Didelot,

I am trying to use BactDating and I have a couple of questions about the tip dating that I would like calrification on.

I have 170 isolates of potato pathogenic bacteria (_Ralstonia solanacearum_) sampled over 26 years from contaminated river water in the UK. I have estimated that all of them belong to a very closely related clonal group and are thus quite similar to each other with core  SNPs range of 0-18. Therefore, a phylogeny of these isolates is weak and has no bootstrap support. My question is whether this data is insufficient to produce meaningful dating with BactDating and is there a minimum number of informative sites the aligment needs to have. I assume single outbreak studies should have a similar issue!

I have used Snippy to call SNPs and make a core gene alignement and Gubbins to remove recombination and construct a tree. Then I rooted the phylogeny using initRoot and ran the root to ti regression test (see below).
![image](https://user-images.githubusercontent.com/38460574/122383754-02c35600-cf63-11eb-8732-dea893fd115f.png)

Cheers, 
Martina

**Comment by xavierdidelot** [comment]
Hi Martina,
Based on the figure you attached, it seems that the temporal signal should be strong enough, but note that this type of root-to-tip analysis is only a really rough way to capture the temporal signal and can often be misleading one way or the other. I think you should try running the bactdate command and see if the results make sense. You can then use better methods to test the temporal signal, see an example at the bottom of the page https://xavierdidelot.github.io/BactDating/articles/exampleTest.html
Best wishes,
Xavier
