### ISSUE TITLE
Missing dates

### ISSUE THREAD

**Issue by LeonardosMageiros** [xavierdidelot/BactDating#47]
Hi! 

I have the clonalframeML output for ~1500 strains and I would like to run bactdating. 
My problem is that some of the strains (around 60) dont have a sampling date assigned to them so the values are actually NA. 

Can bactating handle that situation somehow or I must rerun clonalframeML only using the strains that have a date assigned to them?

Thank you very much in advance
Leonardos

**Comment by xavierdidelot** [comment]
Hi Leonardos! Yes BactDating can deal with missing dates. If you leave them as NA, BactDating will understand that the date is missing. There could be an issue if too many dates are missing, but having only around 60 missing out of 1500 should be no problem at all.

**Comment by LeonardosMageiros** [comment]
Xavier thank you very much!
