### ISSUE TITLE
effectiveSize function from coda package cannot read object from

### ISSUE THREAD

**Issue by hcc14** [xavierdidelot/BactDating#51]
Hi, 
I was trying to run BactDating and checking the effective size, but it looks like an issue in the conversion to an mcmc object

`library(coda)`
`library(BactDating)`
`res = bactdate(unroot(nwk_tree), collectionTime, nbIts=1e5, showProgress = T)`
`mcmc = as.mcmc(res)`
`effectiveSize(mcmc)`
Error in character(ncol(y)) : invalid 'length' argument

> packageVersion("BactDating")
[1] ‘1.1.0’
> packageVersion("coda")
[1] ‘0.19.4’

**Comment by xavierdidelot** [comment]
It should work if you replace the line 4 with:
`mcmc=as.mcmc.resBactDating(res)`
