### ISSUE TITLE
Extract isolation dates from tip labels

### ISSUE THREAD

**Issue by amymariecampbell** [xavierdidelot/BactDating#54]
Hi there, 

My isolation dates are contained within my sample names- is there a way to extract these instead of having to create a list in the right order? 

My tip labels are in the format XXXXX_yyyy-m-dd_XXXX. 

Thanks!

**Comment by xavierdidelot** [comment]
Yes it's definitely possible to extract the dates from your labels. First you need to extract the year, month and day using something like `regexpr`. Then you need to convert this into a decimal year either using a formula like `decimalyear=year+(month-1)/12+(day-1)/365` or using `decimal_date` from the `lubridate` package.
