### ISSUE TITLE
#Acquire the estimated time for each node and add time axis when plotting the result tree 

### ISSUE THREAD

**Issue by QianGuoPKU** [xavierdidelot/BactDating#55]
Hi,

Thanks for providing such excellent tool!
My question is, how to acquire the estimated time for each node? As i understand, BactDating can output the CI intervals. But I also need the estimation in addition to the CI intervals. And, do you have some idea to add the time axis when plotting the res$tree?

I would appreciate if you could reply!

Best,
Qian

**Comment by xavierdidelot** [comment]
The `res$tree` contains the point estimate of each node date. If you use `plot(res)` instead of `plot(res$tree)` the tree will be shown with the time axis. You can also use `plot(res,'treeCI')` to show the credible intervals.
