### ISSUE TITLE
Bacdating not installed on R 

### ISSUE THREAD

**Issue by krishna1925** [xavierdidelot/BactDating#57]
Hi!, 
I tried to install Bactdating on my version 3.6. However, I got following error ! Could you please help me to fix this issue asap?

Here is the error I got:

 
> install.packages('devtools')
WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
Installing package into ‘C:/Users/Dell/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/devtools_2.4.3.zip'
Content type 'application/zip' length 423764 bytes (413 KB)
downloaded 413 KB

package ‘devtools’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Dell\AppData\Local\Temp\Rtmp0spI4d\downloaded_packages
> 
> 
> devtools::install_github("xavierdidelot/BactDating")
Downloading GitHub repo xavierdidelot/BactDating@HEAD
√  checking for file 'C:\Users\Dell\AppData\Local\Temp\Rtmp0spI4d\remotes1e1c6f9f488d\xavierdidelot-BactDating-b878d6b/DESCRIPTION' ...
-  preparing 'BactDating': (981ms)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
   Removed empty directory 'BactDating/figures'
-  building 'BactDating_1.1.0.tar.gz'
   
Installing package into ‘C:/Users/Dell/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
* installing *source* package 'BactDating' ...
** using staged installation
** libs

*** arch - i386
Warning in system(cmd) : 'make' not found
ERROR: compilation failed for package 'BactDating'
* removing 'C:/Users/Dell/Documents/R/win-library/4.1/BactDating'
Warning message:
**In i.p(...) :
  installation of package ‘C:/Users/Dell/AppData/Local/Temp/Rtmp0spI4d/file1e1c9527725/BactDating_1.1.0.tar.gz’ had non-zero exit status**

**Comment by xavierdidelot** [comment]
I think this is not a problem specific with BactDating, but rather a problem on your system with installing R packages that include C code. You should probably try installing the `Rcpp` package and/or the Rtools from `https://cran.r-project.org/bin/windows/Rtools/`
