### ISSUE TITLE
ML tree to coalescent tree

### ISSUE THREAD

**Issue by mushalallam** [xavierdidelot/BactDating#6]
Hi,
can I import a maximum likelihood tree to BactDating? or convert it to coalescent tree ?
Thanks in advance
Mushal

**Comment by xavierdidelot** [comment]
Yes a ML tree computer for example using raxml or phyml is a perfectly valid input.
The only thing to be careful about is that branch lengths need to be measured in units of substitutions, not substitutions per site. You can often achieve this simply by multiplying all branch lengths with the number of sites L in your genomes, for example in R using something like:
tree$edge.length=tree$edge.length*L
If you forget to do this there should be a warning in BactDating to remind you.
