### ISSUE TITLE
the node data on exported plot

### ISSUE THREAD

**Issue by chaolv123** [xavierdidelot/BactDating#63]
Dear prof Xavier Didelot:
        In my exported plot, we want to show node data on the plot, though we got the node date used the code in 29#, but we failed in showing on the exported plot, could you share the code? thanks !
    Chao

**Comment by xavierdidelot** [comment]
The code in #29 can be used to obtain the credible intervals for all nodes. To show this on the tree you can do simply `plot(res,'treeCI')`. For anything more advanced you can use `as.treedata.resBactDating` to export the result as a a `treedata` object from the `ggtree` package.
