### ISSUE TITLE
Uncertain error message

### ISSUE THREAD

**Issue by MaitiuMarm** [xavierdidelot/BactDating#66]
Hey there
First up, thanks for an awesome programme. Really useful in this field. I have been getting a persistent error message when attempting to run the backdating command from a RootedTree and an array of dates, which usually end with the message ' Error in if (log(runif(1)) < l2 - l + dgamma(mu2, shape = 0.001, scale = 1000,  :  missing value where TRUE/FALSE needed '.  I have attempted to run this command with every possible input set to TRUE, but this message persists. I start with a tree.nwk, normalize the edge lengths, then root the tree via initRoot and my date array. The root to tip analysis then works fine, but the bactdating fails with a similar TRUE/FALSE missing error every time. I have tried unrooting the tree, not altering the branch lengths, and using the most basic input, but this error persists. Thanks for any help you can give!
Maitiú

**Comment by xavierdidelot** [comment]
Hi Maitiú,
I would need to reproduce the error on my side to see what is causing it. Could you send me your files by email?
Best wishes,
Xavier

**Comment by MaitiuMarm** [comment]
Hey Xavier!Thanks for getting back to me; i managed to resolve it through several session restarts over the last week, and meant to delete the query this morning . I unfortunately cannot find the log file of the error, but the input did not change. Possibly loading and unloading the environment resolved this issueThanks again for your program and patience!Maitiú On 6 Nov 2023, at 09:31, Xavier Didelot ***@***.***> wrote:﻿
Hi Maitiú,
I would need to reproduce the error on my side to see what is causing it. Could you send me your files by email?
Best wishes,
Xavier
