### ISSUE TITLE
Bactdating not recognising names as complete command

### ISSUE THREAD

**Issue by appliedmicrobiologyresearch** [xavierdidelot/BactDating#71]
I have 632 isolates in an alignment to analyse. The names and dates are as below. I am not getting recognition of the names as a complete command, ie the prompt doesn't return but instead just "+". Is there an obvious error I am missing? Thanks!:
d=c('NA',2021,2021,2021,2020,2020,2022,2022,2022,2021,2022,2022,2021,2021,2021,2021,2022,2022,2021,2022,2021,2022,2021,2021,2021,2021,2021,2022,2022,2022,2022,2022,2022,2022,2022,2022,2023,2022,2022,2023,2022,2021,2022,2022,2022,2022,2022,2021,2022,2018,2018,2019,2019,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2023,2023,2023,2023,2023,2023,2023,2023,2023,2023,2023,2023,2023,2023,2022,2022,2022,2022,2022,2022,2022,2022,2022,2023,2022,2022,2022,2022,2022,2022,2022,2023,'NA',2021,2021,2023,2020,2020,2020,2020,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021,2020,2020,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021,2020,2021,2021,2020,2020,2021,2021,2021,2021,2021,2021,2021,2022,2022,2022,2022,2022,2022,2022,2021,2022,2022,2022,2022,2022,2020,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021,2022,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2019,2019,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2020,2022,2022,2022,2022,2022,2022,2022,2020,2022,2022,2022,2022,2022,2022,2022,2022,2022,2020,2020,2022,2020,2022,2022,2022,2022,2022,2022,2022,2022,2019,2022,2022,2022,2022,2019,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2020,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2020,2022,2020,2020,2020,2022,2022,2022,2022,2020,2022,2022,2022,2022,2022,2022,2020,2022,2022,2020,2022,2022,2022,2022,2022,2022,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2019,2020,2020,2020,2020,2020,2019,2020,2020,2020,2020,2020,2020,2020,2019,2020,2020,2020,2020,2020,2020,2020,2020,2020,2018,2018,2020,2020,2020,2020,2020,2020,2020,2021,2021,2021,2021,2021,2021,2021,2020,2020,2021,2021,2021,2021,2021,2021,2021,2021,2020,2021,2021,2020,2020,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021,2020,2021,2021,2021,2021,2019,2021,2019,2021,2019,2021,2021,2021,2021,2021,2021,2021,2021,2021,2020,2020,2021,2021,2021,2021,2021,2021,2021,2020,2021,2021,2021,2021,2021,2021,2021,2020,2020,2021,2021,2021,2021,2021,2020,2021,2021,2020,2020,2020,2020,2020,2020,2020,2021,2021,2021,2021,2021,2021,2020,2021,2021,2021,2021,2020,2021,2021,2021,2020,2021,2020,2020,2019,2019,2021,2021,2021,2021,2020,2021,2021,2021,2020,2021,2021,2020,2021,2021,2020,2021,2021,2021,2021,2021,2021,2020,2021,2020,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021,2020,2020,2021,2021,2021,2021,2021,2021,2021,2021,2021,2020,2021,2021,2020,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021,2019,2019,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021,2022,2022,2022)
names(d)=c('23U12531','23U10468','23U10470','23U10471','23U10473','23U10475','23U10477','23U10478','23U10479','23U10482','23U10483','23U10486','23U10487','23U10488','23U10490','23U10491','23U10494','23U10495','23U10496','23U10497','23U10498','23U10499','23U10502','23U10504','23U10506','23U10507','23U10509','23U11349','23U11350','23U11352','23U11354','23U11356','23U12156','23U12564','23U167','23U169','23U2276','23U249','23U251','23U3812','A22830','A22831','A22832','A22833','A22834','A22835','A22836','A22837','A510318','D6593','D6594','D6595','D6596','D6597','D6598','D6599','D6600','D6601','D6602','D6603','D6604','D6605','D6606','D6607','D6608','D6609','D6610','D6611','D6612','D6613','D6614','D6615','D6616','D6617','D6618','D6620','D6621','D6622','D6623','D6624','D6625','D6626','D6627','D6629','D6630','D6631','D6632','D6633','D6634','D6635','D6636','D6637','D6638','D6639','D6640','D6641','D6642','D6643','D6644','D6645','D6646','D6647','D6648','D6650','D6651','D6652','D6653','D6654','D6655','D6656','D6657','D6658','D6659','D6660','D6661','D6662','D6663','D6664','D6665','D6666','D6667','D6668','D6669','D6670','D6671','D6672','D6673','D6674','D6675','D6676','D6677','D6678','D6679','D6680','D6681','D6682','D6683','D6684','D6685','D6686','D6687','D6688','D6689','D6690','D6691','D6692','D6693','D6694','D6695','D6697','D6698','D6699','D6700','D6702','U10185','U10187','U10193','U10205','U10241','U10244','U10303','U10440','U10445','U10603','U10605','U10611','U10722','U10724','U108','U10834','U11114','U11258','U11260','U11295','U11296','U11298','U11317','U11319','U11330','U11333','U11336','U11382','U11388','U11424','U11631','U120','U12100','U12112','U12125','U12126','U12128','U12146','U12193','U12278','U12281','U12291','U12449','U12452','U12453','U12454','U12458','U12465','U12471','U12477','U12481','U12498','U126','U12851','U12853','U12857','U12864','U12870','U12871','U13019','U13025','U13027','U13030','U13033','U13108','U13180','U13228','U13276','U13312','U13336','U13384','U13485','U13550','U13564','U13571','U13577','U13578','U13580','U13608','U13617','U13716','U13729','U13732','U13741','U13753','U13756','U13764','U13771','U13773','U13778','U13782','U14024','U14119','U14123','U14125','U14129','U14130','U14136','U14137','U14138','U14142','U14149','U14150','U14151','U14152','U14154','U14155','U14158','U14163','U14164','U14166','U14277','U14278','U14292','U14309','U14356','U14547','U14597','U14720','U14774','U14828','U14838','U14842','U14843','U15215','U15243','U15248','U15282','U15288','U15294','U15324','U15444','U15474','U15557','U15578','U158','U15849','U16196','U16254','U16310','U16312','U16348','U16717','U1676','U16761','U16843','U16847','U16848','U16852','U16854','U16857','U16967','U17045','U1707','U1708','U17082','U1710','U17121','U17172','U17174','U17175','U17176','U17186','U17196','U17418','U1746','U17476','U17484','U17485','U17493','U1751','U17519','U17522','U17525','U17526','U17579','U17809','U17811','U17812','U17818','U17822','U17826','U1820','U18221','U18232','U18242','U18244','U18251','U18487','U18490','U18496','U18849','U18908','U19179','U19180','U19197','U19201','U19236','U19240','U19564','U19571','U19573','U19719','U19721','U19731','U19738','U19748','U19750','U19752','U1978','U19789','U1979','U1981','U1983','U19931','U19934','U19939','U19946','U1999','U20032','U20078','U20080','U20085','U20086','U20233','U2024','U20356','U20363','U2039','U20397','U20398','U20557','U20558','U20561','U20583','U207','U2079','U2086','U2156','U2162','U2189','U2365','U2368','U2369','U2372','U2375','U2377','U2388','U2393','U2396','U2399','U2402','U2404','U2409','U241','U2410','U2412','U2413','U2420','U2426','U2432','U2466','U247','U2484','U2485','U2490','U2499','U2566','U2618','U2728','U2839','U2841','U3339','U3783','U3966','U398','U3997','U4235','U4260','U4563','U4676','U4687','U4758','U4761','U4813','U4815','U499','U4993','U4994','U5011','U504','U5050','U5056','U5059','U5107','U5109','U5125','U5135','U516','U519','U5239','U5240','U5302','U5303','U5321','U5328','U5362','U5437','U544','U5568','U5576','U583','U586','U5943','U5948','U5974','U5979','U5995','U5999','U6009','U6014','U6025','U6133','U6134','U6145','U6217','U6288','U6378','U646','U6489','U6505','U6508','U6519','U659','U6653','U666','U6667','U668','U6962','U6966','U6968','U6971','U6972','U6974','U6993','U6994','U6995','U7','U70','U7022','U7028','U7029','U7047','U7058','U7134','U7138','U721','U7327','U7332','U7334','U7348','U7361','U7362','U7378','U742','U745','U7477','U7545','U7571','U7599','U7605','U764','U7676','U7677','U7700','U7705','U7708','U7711','U7713','U7717','U7718','U7761','U7770','U7774','U7799','U7800','U7843','U7903','U7910','U7931','U7935','U7937','U794','U7946','U7950','U7951','U796','U7964','U797','U80','U8017','U8068','U8130','U8133','U8231','U8232','U8298','U8321','U8322','U8349','U838','U8408','U8409','U842','U8420','U8426','U844','U8538','U8545','U8551','U8558','U8633','U8658','U870','U8714','U872','U8724','U8758','U8764','U8767','U8908','U8949','U9105','U9108','U9109','U9120','U9134','U9257','U9282','U9283','U9294','U9376','U9496','U9500','U9512','U9516','U9541','U9542','U9562','U959','U9602','U9632','U966','U9683','U9685','U9721','U9830','U9837','U9987','U9990','U9994','U9997','U9999','UW20561','UW20652','UW20769','UW20856','UW20878','UW21192','UW21208','UW21316','UW21319','UW21321','UW21370','UW21371','UW21389','UW21390','UW21393','UW21930','UW21932','UW22086','UW22105','UW22203','UW22229','UW22231','UW22233','UW22234','UW22236','UW22242','UW22368','UW22433','UW22452','UW22453','UW22560','UW22578','UW23031','UW23033','UW23034')

**Comment by xavierdidelot** [comment]
Your problem is that your second line has 5594 characters whereas the maximum number of characters accepted by R in a single line of input is 4094.
If you split the second line in two around the middle then it should work fine.

**Comment by appliedmicrobiologyresearch** [comment]
Thanks millions! Too much data ;-)
